package IO::K8s::ExternalSecrets::V1::OnboardbaseAuthSecretRef;
# ABSTRACT: Auth configures how the Operator authenticates with the Onboardbase API
our $VERSION = '1.108';
use IO::K8s::Resource;

k8s apiKeyRef   => '+IO::K8s::ExternalSecrets::V1::SecretKeySelector', { required => 'schema' };
k8s passcodeRef => '+IO::K8s::ExternalSecrets::V1::SecretKeySelector', { required => 'schema' };

=attr apiKeyRef

OnboardbaseAPIKey is the APIKey generated by an admin account.
It is used to recognize and authorize access to a project and environment within onboardbase

=cut

=attr passcodeRef

OnboardbasePasscode is the passcode attached to the API Key

=cut

1;
