package IO::K8s::ExternalSecrets::V1alpha1::GrafanaServiceAccount;
# ABSTRACT: ServiceAccount is the configuration for the service account that is supposed to be generated by the generator.
our $VERSION = '1.108';
use IO::K8s::Resource;

k8s name          => Str, { required => 'schema' };
k8s role          => Str, { required => 'schema' };
k8s secondsToLive => Int, { minimum => 1 };

=attr name

Name is the name of the service account that will be created by ESO.

=cut

=attr role

Role is the role of the service account.
See here for the documentation on basic roles offered by Grafana:
https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/

=cut

=attr secondsToLive

SecondsToLive is the number of seconds before the generated service account token will expire.
Some Grafana deployments (e.g. AWS Managed Grafana) require this value to be set.

=cut

1;
