package IO::K8s::ExternalSecrets::V1alpha1::GrafanaSpec;
# ABSTRACT: GrafanaSpec controls the behavior of the grafana generator.
our $VERSION = '1.108';
use IO::K8s::Resource;

k8s auth           => '+IO::K8s::ExternalSecrets::V1alpha1::GrafanaAuth', { required => 'schema' };
k8s serviceAccount => '+IO::K8s::ExternalSecrets::V1alpha1::GrafanaServiceAccount', { required => 'schema' };
k8s url            => Str, { required => 'schema' };

=attr auth

Auth is the authentication configuration to authenticate
against the Grafana instance.

=cut

=attr serviceAccount

ServiceAccount is the configuration for the service account that
is supposed to be generated by the generator.

=cut

=attr url

URL is the URL of the Grafana instance.

=cut

1;
