package IO::K8s::Api::Certificates::V1::PodCertificateRequestSpec;
# ABSTRACT: PodCertificateRequestSpec describes the certificate request. All fields are immutable after creation.
our $VERSION = '1.108';
use IO::K8s::Resource;

k8s maxExpirationSeconds => Int;

=attr maxExpirationSeconds

maxExpirationSeconds is the maximum lifetime permitted for the certificate.

If omitted, kube-apiserver will set it to 86400(24 hours). kube-apiserver will reject values shorter than 3600 (1 hour).  The maximum allowable value is 7862400 (91 days).

The signer implementation is then free to issue a certificate with any lifetime *shorter* than MaxExpirationSeconds, but no shorter than 3600 seconds (1 hour).  This constraint is enforced by kube-apiserver. `kubernetes.io` signers will never issue certificates with a lifetime longer than 24 hours.

=cut

k8s nodeName => Str, 'required';

=attr nodeName

nodeName is the name of the node the pod is assigned to.

=cut

k8s nodeUID => Str, 'required';

=attr nodeUID

nodeUID is the UID of the node the pod is assigned to.

=cut

k8s podName => Str, 'required';

=attr podName

podName is the name of the pod into which the certificate will be mounted.

=cut

k8s podUID => Str, 'required';

=attr podUID

podUID is the UID of the pod into which the certificate will be mounted.

=cut

k8s serviceAccountName => Str, 'required';

=attr serviceAccountName

serviceAccountName is the name of the service account the pod is running as.

=cut

k8s serviceAccountUID => Str, 'required';

=attr serviceAccountUID

serviceAccountUID is the UID of the service account the pod is running as.

=cut

k8s signerName => Str, 'required';

=attr signerName

signerName indicates the requested signer.

All signer names beginning with `kubernetes.io` are reserved for use by the Kubernetes project.  There is currently one well-known signer documented by the Kubernetes project, `kubernetes.io/kube-apiserver-client-pod`, which will issue client certificates understood by kube-apiserver.  It is currently unimplemented.

=cut

k8s stubPKCS10Request => Str, 'required';

=attr stubPKCS10Request

A PKCS#10 certificate signing request (DER-serialized) generated by Kubelet using the subject private key.

Most signer implementations will ignore the contents of the CSR except to extract the subject public key. The API server automatically verifies the CSR signature during admission, so the signer does not need to repeat the verification.  CSRs generated by kubelet are completely empty.

The subject public key must be one of RSA3072, RSA4096, ECDSAP256, ECDSAP384, ECDSAP521, or ED25519. Note that this list may be expanded in the future.

Signer implementations do not need to support all key types supported by kube-apiserver and kubelet.  If a signer does not support the key type used for a given PodCertificateRequest, it must deny the request by setting a status.conditions entry with a type of "Denied" and a reason of "UnsupportedKeyType". It may also suggest a key type that it does support in the message field.

=cut

k8s unverifiedUserAnnotations => { Str => 1 };

=attr unverifiedUserAnnotations

unverifiedUserAnnotations allow pod authors to pass additional information to the signer implementation.  Kubernetes does not restrict or validate this metadata in any way.

Entries are subject to the same validation as object metadata annotations, with the addition that all keys must be domain-prefixed. No restrictions are placed on values, except an overall size limitation on the entire field.

Signers should document the keys and values they support.  Signers should deny requests that contain keys they do not recognize.

=cut

1;
